# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-04-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210405_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_theme',
            field=models.CharField(max_length=64, verbose_name='站点样式'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatar/default.png', upload_to='avatar/', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
    ]
